/**
 * Google Gemini API integration for content generation
 */

const GEMINI_API_KEY = 'AIzaSyBBFyqGFV-WGgUZim9crNCESPzFe-jIQSs';
const GEMINI_API_URL = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent';

interface GeminiResponse {
  candidates: {
    content: {
      parts: {
        text: string;
      }[];
    };
  }[];
}

export async function generateContent(prompt: string, type: 'article' | 'brief'): Promise<string> {
  if (!GEMINI_API_KEY) {
    console.warn('Gemini API key not found, using placeholder content');
    return getPlaceholderContent(prompt, type);
  }

  try {
    const systemPrompt = type === 'article' 
      ? `You are an expert content writer and SEO specialist. Create a comprehensive, well-structured article about the given topic. Use HTML formatting with proper headings (h2, h3), paragraphs, lists, and other elements. Make the content engaging, informative, and SEO-friendly. Aim for 800-1200 words. Include relevant keywords naturally throughout the content.`
      : `You are a content strategist. Create a detailed content brief for the given topic. Include target audience, key points to cover, suggested outline, tone recommendations, and SEO considerations. Format as a structured response with clear sections.`;

    const userPrompt = type === 'article'
      ? `Write a comprehensive, SEO-optimized article about: ${prompt}. Include proper HTML structure with headings, paragraphs, and lists. Make it engaging and informative.`
      : `Create a detailed content brief for: ${prompt}. Include target audience, outline, key points, tone, and SEO recommendations.`;

    const requestBody = {
      contents: [
        {
          role: "user",
          parts: [
            {
              text: `${systemPrompt}\n\n${userPrompt}`
            }
          ]
        }
      ]
    };

    const response = await fetch(`${GEMINI_API_URL}?key=${GEMINI_API_KEY}`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(requestBody),
    });

    if (!response.ok) {
      if (response.status === 429) {
        throw new Error('Gemini API rate limit exceeded. Please wait a few minutes before trying again.');
      }
      if (response.status === 401) {
        throw new Error('Invalid Gemini API key. Please check your configuration.');
      }
      throw new Error(`Gemini API error: ${response.status} ${response.statusText}`);
    }

    const data: GeminiResponse = await response.json();
    const content = data.candidates?.[0]?.content?.parts?.[0]?.text;

    if (!content) {
      throw new Error('No content generated from Gemini');
    }

    return content;
  } catch (error) {
    console.error('Error generating content with Gemini:', error);
    
    // Re-throw specific errors
    if (error instanceof Error && (
      error.message.includes('rate limit') || 
      error.message.includes('API key') ||
      error.message.includes('Gemini API error')
    )) {
      throw error;
    }
    
    // Fallback to placeholder content for other errors
    console.warn('Falling back to placeholder content due to error:', error);
    return getPlaceholderContent(prompt, type);
  }
}

function getPlaceholderContent(prompt: string, type: 'article' | 'brief'): string {
  if (type === 'article') {
    return `
      <h2>Introduction to ${prompt}</h2>
      <p>This is a comprehensive guide about "${prompt}". This content demonstrates the structure and format that would be generated by AI, providing valuable insights and actionable information for readers interested in this topic.</p>
      
      <h2>Understanding ${prompt}</h2>
      <p>To fully grasp the concept of ${prompt}, it's important to understand its core principles and applications. This topic has gained significant attention due to its practical benefits and wide-ranging implications across various industries and use cases.</p>
      
      <h3>Key Components</h3>
      <ul>
        <li><strong>Foundation:</strong> The basic principles underlying ${prompt}</li>
        <li><strong>Implementation:</strong> How to effectively apply ${prompt} in practice</li>
        <li><strong>Optimization:</strong> Best practices for maximizing results</li>
        <li><strong>Measurement:</strong> Tracking success and making improvements</li>
      </ul>
      
      <h2>Benefits and Advantages</h2>
      <p>Implementing ${prompt} can provide numerous benefits for individuals and organizations looking to improve their processes and outcomes:</p>
      
      <h3>Primary Benefits</h3>
      <ol>
        <li><strong>Efficiency:</strong> Streamlined processes and improved productivity</li>
        <li><strong>Quality:</strong> Enhanced outcomes and better results</li>
        <li><strong>Scalability:</strong> Ability to grow and adapt over time</li>
        <li><strong>Innovation:</strong> New opportunities and creative solutions</li>
      </ol>
      
      <h2>Best Practices and Implementation</h2>
      <p>To successfully implement ${prompt}, consider these proven strategies and approaches that have been tested by industry leaders:</p>
      
      <h3>Getting Started</h3>
      <p>Begin with a clear understanding of your goals and requirements. Develop a structured plan that includes timelines, resources, and success metrics to ensure effective implementation.</p>
      
      <h3>Common Challenges</h3>
      <p>While implementing ${prompt}, you may encounter various challenges. Here are some common issues and their solutions:</p>
      <ul>
        <li><strong>Resource constraints:</strong> Plan and allocate resources effectively</li>
        <li><strong>Technical complexity:</strong> Break down complex tasks into manageable steps</li>
        <li><strong>Team alignment:</strong> Ensure clear communication and shared objectives</li>
        <li><strong>Change management:</strong> Prepare for and manage organizational changes</li>
      </ul>
      
      <h2>Future Trends and Considerations</h2>
      <p>The landscape of ${prompt} continues to evolve rapidly. Stay informed about emerging trends and technologies that may impact your approach and strategy in the coming years.</p>
      
      <h3>Emerging Technologies</h3>
      <p>Keep an eye on new developments that could enhance or transform how ${prompt} is implemented and utilized across different sectors.</p>
      
      <h2>Conclusion</h2>
      <p>In conclusion, ${prompt} represents a valuable opportunity for growth and improvement. By understanding its principles, implementing best practices, and staying adaptable to change, you can achieve significant success in this area.</p>
      
      <p>Remember that success with ${prompt} requires ongoing commitment, continuous learning, and regular evaluation of your progress. Start with small steps, measure your results, and scale your efforts as you gain experience and confidence.</p>
      
      <h3>Next Steps</h3>
      <p>To get started with ${prompt}, consider taking these immediate actions:</p>
      <ul>
        <li>Assess your current situation and identify opportunities</li>
        <li>Set clear, measurable goals and objectives</li>
        <li>Develop a timeline and action plan</li>
        <li>Begin with a pilot project or small-scale implementation</li>
        <li>Monitor progress and adjust your approach as needed</li>
      </ul>
    `;
  } else if (type === 'brief') {
    return `
      <h3>Content Brief: ${prompt}</h3>
      
      <h4>Target Audience</h4>
      <p>Business professionals, decision-makers, and individuals interested in learning about ${prompt} and its practical applications.</p>
      
      <h4>Content Outline</h4>
      <ol>
        <li>Introduction and overview of ${prompt}</li>
        <li>Key concepts and terminology</li>
        <li>Benefits and advantages</li>
        <li>Implementation strategies</li>
        <li>Best practices and tips</li>
        <li>Common challenges and solutions</li>
        <li>Future trends and considerations</li>
        <li>Conclusion and next steps</li>
      </ol>
      
      <h4>Key Points to Cover</h4>
      <ul>
        <li>Define ${prompt} and its importance</li>
        <li>Explain practical applications and use cases</li>
        <li>Provide actionable insights and recommendations</li>
        <li>Address common concerns and objections</li>
        <li>Include relevant examples and case studies</li>
      </ul>
      
      <h4>Tone and Style</h4>
      <p>Professional yet approachable, informative but not overly technical. Use clear, concise language that is accessible to the target audience.</p>
      
      <h4>SEO Considerations</h4>
      <ul>
        <li>Primary keyword: ${prompt}</li>
        <li>Secondary keywords: ${prompt} guide, ${prompt} tips, ${prompt} best practices</li>
        <li>Target word count: 800-1200 words</li>
        <li>Include relevant internal and external links</li>
        <li>Use proper heading structure (H1, H2, H3)</li>
      </ul>
    `;
  }
  
  return `Generated content for: ${prompt}`;
}